platform :ios, '8.0'
use_frameworks!

target 'Congress2’ do
pod 'Alamofire', '~> 4.2'
pod 'AlamofireImage', '~> 3.2'
pod 'SwiftyJSON', '~> 3.1'
pod 'SwiftSpinner', '~> 1.1'
pod 'SlideMenuControllerSwift'
end
